- src/main/webapp/WEB-INF/views/admin.jsp
- src/main/webapp/WEB-INF/views/index.jsp
- src/main/webapp/static/css/admin.css
- src/main/webapp/static/css/index.css
- src/main/webapp/static/js/admin.js
- src/main/webapp/static/js/index.js
[Update] 更新了管理员登录和顾客登录，增加注释，规范引入。
> [Update] 更新了管理员登录和顾客登录

- src/main/webapp/static/js/register.js
> [Fixed] 修复了注册页面提交失败的问题

- src/main/java/com/bean/Commodity.java
> [Update] 更新了商品实体类

- src/main/webapp/admin.jsp
- src/main/webapp/login.jsp
- src/main/webapp/static/css/admin.css
- src/main/webapp/static/css/login.css
- src/main/webapp/static/js/admin.js
- src/main/webapp/static/js/login.js
[Update] 更新了用户登录、后台登录界面验证、页面样式。
> [Update] 更新了用户登录、后台登录界面及验证

- src/main/webapp/login.jsp
- src/main/webapp/static/css/login.css
> [Fixed] 修复了用户登录无法跳转界面的问题

- src/main/webapp/WEB-INF/views/password.jsp
- src/main/webapp/static/css/password.css
- src/main/webapp/static/js/password.js
[Create] 新建了个人中心-修改密码界面、样式、验证。
> [Create] 新建了个人中心-修改密码部分

- src/main/webapp/index.jsp
- src/main/webapp/static/css/index.css
> [Update] 修改了首页界面样式及访问路径

- src/main/webapp/WEB-INF/views/userindex.jsp
- src/main/webapp/static/css/admin.css
- src/main/webapp/static/css/login.css
> [Update] 更新了用户登录、管理员登录界面样式 

- src/main/webapp/WEB-INF/views/car.jsp
- src/main/webapp/WEB-INF/views/details.jsp
- src/main/webapp/WEB-INF/views/password.jsp
- src/main/webapp/WEB-INF/views/self.jsp
- src/main/webapp/WEB-INF/views/sort.jsp
- src/main/webapp/WEB-INF/views/userindex.jsp
- src/main/webapp/index.jsp
- src/main/webapp/static/css/car.css
- src/main/webapp/static/css/details.css
- src/main/webapp/static/css/sort.css
- src/main/webapp/static/js/car.js
- src/main/webapp/static/js/details.js
- src/main/webapp/static/js/sort.js
[Create] 新建了购物车页面样式
[Create] 新建了购物车操作
[Create] 新建了购物车界面
[Create] 新建了商品详情界面样式
[Create] 新建了商品详情操作
[Create] 新建了商品详情界面
[Update] 更新了主页界面跳转路径
[Update] 更新了修改密码界面跳转路径
[Update] 更新了个人中心界面跳转路径
[Create] 新建了分类界面样式
[Create] 新建了分类界面商品显示遍历
[Create] 新建了分类界面
[Update] 更新了用户登录后页面跳转路径
> [Create] 新建了购物车、商品详情、分类页面 [Update] 更新了主页、个人中心页、用户登录后页面的跳转

- src/main/webapp/WEB-INF/views/car.jsp
- src/main/webapp/WEB-INF/views/details.jsp
- src/main/webapp/WEB-INF/views/password.jsp
- src/main/webapp/WEB-INF/views/self.jsp
- src/main/webapp/WEB-INF/views/sort.jsp
- src/main/webapp/WEB-INF/views/userindex.jsp
- src/main/webapp/static/css/car.css
- src/main/webapp/static/css/details.css
- src/main/webapp/static/css/index.css
- src/main/webapp/static/css/password.css
- src/main/webapp/static/css/self.css
- src/main/webapp/static/css/sort.css
- src/main/webapp/static/js/details.js
- src/main/webapp/static/js/index.js
[Update] 更新了所有页面用户名显示和退出功能及其样式以及购物车和商品详情界面
> [Update] 更新了用户名显示和退出功能及其样式，购物车和商品详情界面

- src/main/webapp/static/js/details.js
- src/main/webapp/static/js/index.js
[Update] 更新了商品详情图片id，首页商品详情跳转路径
> [Update] 更新了商品详情图片id，首页商品详情跳转路径

- src/main/webapp/WEB-INF/views/car.jsp
- src/main/webapp/WEB-INF/views/details.jsp
- src/main/webapp/WEB-INF/views/password.jsp
- src/main/webapp/WEB-INF/views/self.jsp
- src/main/webapp/WEB-INF/views/sort.jsp
- src/main/webapp/WEB-INF/views/userOrder.jsp
- src/main/webapp/WEB-INF/views/userindex.jsp
- src/main/webapp/static/css/userOrder.css
- src/main/webapp/static/js/car.js
- src/main/webapp/static/js/details.js
- src/main/webapp/static/js/index.js
- src/main/webapp/static/js/self.js
- src/main/webapp/static/js/userOrder.js
[Update] 更新了页面用户名显示，商品详情页面购物车操作，页面跳转路径。 [Create] 新增了我的订单界面。
> [Update] 更新了页面用户名显示，商品详情页面购物车操作，页面跳转路径。 [Create] 新增了我的订单界面。 

- src/main/java/com/servlet/manager/ManagerLoginServlet.java
- src/main/webapp/WEB-INF/views/commodity.jsp
- src/main/webapp/WEB-INF/views/customer.jsp
- src/main/webapp/WEB-INF/views/managerlogin.jsp
- src/main/webapp/WEB-INF/views/order.jsp
- src/main/webapp/static/css/customer.css
- src/main/webapp/static/css/managerlogin.css
- src/main/webapp/static/js/managerlogin.js
[Update] 对后台各界面的样式、跳转方式进行更新和修改，并更新了管理员动态登录[Update] 对后台各界面的样式、跳转方式进行更新和修改，并更新了管理员动态登录。
> [Update] 对后台各界面的样式、跳转方式进行更新和修改，并更新了管理员动态登录

- src/main/webapp/WEB-INF/views/car.jsp
- src/main/webapp/WEB-INF/views/details.jsp
- src/main/webapp/WEB-INF/views/password.jsp
- src/main/webapp/WEB-INF/views/self.jsp
- src/main/webapp/WEB-INF/views/sort.jsp
- src/main/webapp/WEB-INF/views/userOrder.jsp
- src/main/webapp/WEB-INF/views/userindex.jsp
- src/main/webapp/index.jsp
- src/main/webapp/static/css/self.css
- src/main/webapp/static/js/details.js
- src/main/webapp/static/js/password.js
- src/main/webapp/static/js/self.js
- src/main/webapp/static/js/userOrder.js
[Update] 修改了页面获取用户名方式，修改了页面id值和属性名
> [Update] 修改了页面获取用户名方式，修改了页面id值和属性名

- src/main/webapp/WEB-INF/views/details.jsp
- src/main/webapp/WEB-INF/views/self.jsp
- src/main/webapp/WEB-INF/web.xml
- src/main/webapp/index.jsp
- src/main/webapp/static/js/details.js
- src/main/webapp/static/js/index.js
- src/main/webapp/static/js/self.js
> [Update] 修改了首页界面、个人信息修改、商品详情

- src/main/webapp/WEB-INF/views/car.jsp
- src/main/webapp/WEB-INF/views/details.jsp
- src/main/webapp/static/css/car.css
- src/main/webapp/static/css/details.css
- src/main/webapp/static/js/details.js
> [Update] 修改了页面导航栏样式

- src/main/webapp/WEB-INF/views/commodity.jsp
- src/main/webapp/WEB-INF/views/commodityAdd.jsp
- src/main/webapp/WEB-INF/views/order.jsp
- src/main/webapp/static/js/commodity.js
- src/main/webapp/static/js/commodityAdd.js
- src/main/webapp/static/js/order.js
> [Fixed] 修复了代码格式不规范的问题

- src/main/webapp/WEB-INF/views/commodityModify.jsp
- src/main/webapp/static/js/commodityModify.js
> [Update] 更新了与后端对接修改商品信息功能

- src/main/webapp/static/js/commodity.js
- src/main/webapp/static/js/commodityAdd.js
- src/main/webapp/static/js/commodityModify.js
[Update] 更新了增删修改商品信息后自动关闭弹窗及提示增删修改信息成功的功能
> [Update] 更新了增删修改商品信息后自动关闭弹窗及提示增删修改信息成功的功能

- src/main/webapp/static/js/index.js
- src/main/webapp/static/js/result.js
- src/main/webapp/static/js/self.js
> [Update] 修改商品列表显示跳出，注释console

- src/main/webapp/WEB-INF/views/customer.jsp
- src/main/webapp/WEB-INF/views/customerAdd.jsp
- src/main/webapp/WEB-INF/views/customerModify.jsp
- src/main/webapp/static/js/commodity.js
- src/main/webapp/static/js/customer.js
- src/main/webapp/static/js/customerAdd.js
- src/main/webapp/static/js/customerModify.js
> [Update] 更新了根据商品名搜索商品的功能

- src/main/webapp/WEB-INF/views/details.jsp
- src/main/webapp/static/js/car.js
- src/main/webapp/static/js/details.js
- src/main/webapp/static/js/index.js
[Update] 更新了商品加入购物车接口、购物车修改、删除接口
> [Update] 更新了商品加入购物车操作

- src/main/webapp/WEB-INF/views/beforedetails.jsp
- src/main/webapp/WEB-INF/views/beforeresult.jsp
- src/main/webapp/WEB-INF/views/beforesort.jsp
- src/main/webapp/WEB-INF/views/details.jsp
- src/main/webapp/WEB-INF/views/result.jsp
- src/main/webapp/WEB-INF/views/sort.jsp
- src/main/webapp/WEB-INF/views/userindex.jsp
- src/main/webapp/WEB-INF/web.xml
- src/main/webapp/index.jsp
- src/main/webapp/static/css/car.css
- src/main/webapp/static/css/details.css
- src/main/webapp/static/css/index.css
- src/main/webapp/static/css/result.css
- src/main/webapp/static/css/sort.css
- src/main/webapp/static/js/admin.js
- src/main/webapp/static/js/beforedetails.js
- src/main/webapp/static/js/beforeindex.js
- src/main/webapp/static/js/beforeresult.js
- src/main/webapp/static/js/beforesort.js
- src/main/webapp/static/js/car.js
- src/main/webapp/static/js/details.js
- src/main/webapp/static/js/index.js
- src/main/webapp/static/js/login.js
- src/main/webapp/static/js/result.js
- src/main/webapp/static/js/sort.js
- src/main/webapp/static/js/userOrder.js
[Update] 修改了购物车、订单页面操作 [Create] 新增了用户登录前页面
> [Update] 修改了购物车、订单页面操作 [Create] 新增了用户登录前页面

- src/main/java/com/servlet/user/UserRegisterServlet.java
> [Update] 更新注册成功跳转到登录页面

- src/main/webapp/WEB-INF/web.xml
- src/main/webapp/static/js/order.js
[Update] 更新了后台管理员显示订单信息的功能
[Update] 更新了后台编辑用户信息
> [Update] 更新了后台管理员显示订单信息和后台编辑用户信息功能

- src/main/webapp/WEB-INF/views/car.jsp
- src/main/webapp/WEB-INF/views/details.jsp
- src/main/webapp/static/css/car.css
- src/main/webapp/static/js/car.js
- src/main/webapp/static/js/userOrder.js
> [Update] 修改了购物车结算操作、订单页面查询和删除
